api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.views import *

router = routers.DefaultRouter()
router.register(r'sheet', SheetViewSet)
router.register(r'cell', CellViewSet)
router.register(r'instructor', InstructorViewSet)
router.register(r'course', CourseViewSet)
router.register(r'sheet', SheetViewSet)
router.register(r'course-part', CoursePartViewSet)
router.register(r'file', FileItemViewSet)
router.register(r'tag', TagViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

klazor/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from klazor.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Administration views
    path('admin/', admin.site.urls),

    # Authentication views
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='pages/welcome.html'), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', welcome, name='welcome'),
    path('shared-with-me/', view_shared_with_me, name='shared-with-me'),
    url(r'^register/$', register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('course/<int:id>/', view_course, name='course'),
    path('course/<int:course_id>/part/<int:part_sequence>/element/<int:element_sequence>/',
         view_course_element, name='course-element'),
    path('folder/<int:id>/', view_folder, name='folder'),
    path('folder/editor/<int:id>/sheet/<int:sheet_id>', view_folder_editor, name='folder-editor'),
    path('sheet/<int:id>/', view_sheet, name='sheet'),
    path('folder/<int:id>/sheet/new/', add_sheet, name='add-sheet'),
    path('sheet/<int:id>/save/', save_sheet, name='save-sheet'),
    path('sheet/<int:id>/cell/save/', save_cell, name='save-cell'),
    path('item/move/<int:id>/into/<int:destination_id>', move_item, name='move-item'),
    path('item/delete/<int:id>/', delete_item, name='delete-item'),
    path('folder/delete/<int:id>/', delete_folder, name='delete-folder'),
    path('folder/move/<int:id>/into/<int:destination_id>', move_folder, name='move-folder'),
    path('folder/rename/<int:id>/', rename_folder, name='rename-folder'),
    path('course/edit/<int:id>/', edit_course, name='edit-course'),
    path('course/save/<int:id>/', save_course, name='save-course'),
    path('course/<int:course_id>/add-part/', add_course_part, name='add-course-part'),
    path('course-part/<int:course_part_id>/add-element/', add_course_element, name='add-course-element'),
    path('folder/add/', add_folder, name='add-folder'),
    path('tag/add/', add_tag, name='add-tag'),
    path('instructor/add/', add_instructor, name='add-instructor'),
    path('folder/<int:id>/convert/course', convert_folder_to_course, name='folder-to-course'),
    path('folder/file/add/', add_folder_files, name='add-folder-files'),
    path('course/add/into/<int:folder_id>/', add_course, name='add-course'),
    path('upload/', upload, name='upload'),
    path('sheet/<int:id>/print', print_sheet, name='print-sheet'),
    path('course-element/check/<int:id>/', toggle_course_element_status, name='check-course-element'),

    # Libr urls
    url(r'^libr/', include('libr.urls')),
    # Api urls
    url(r'^api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libr/urls.py
from django.urls import path
from libr.views import *

app_name = 'libr'
urlpatterns = [
    path('', index, name='index')
]

klazor/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User
from polymorphic.models import PolymorphicModel


class Tag(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tag'


class Instructor(PolymorphicModel):
    name = models.CharField(max_length=128, blank=True, null=True)
    link = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'instructor'


class Content(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=False)
    # remove null=True for these three
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        abstract = True


class Item(PolymorphicModel, Content):
    tag_set = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=128, blank=True, null=True)
    folder = models.ForeignKey('Folder', null=True, blank=True, on_delete=models.CASCADE)

    def type(self):
        return self.__class__.__name__

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'item'
        ordering = ['id', ]


class FileItem(Item):
    file = models.FileField(upload_to='files', null=True)

    class Meta:
        db_table = 'file'


class Log(models.Model):
    datetime = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class UserItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class UserItemActionLog(Log, UserItem):

    # Defining actions
    VIEWED = 'VI',
    COMPLETED = 'CP'
    SHARE = 'SH'

    ACTIONS = [
        (VIEWED, 'View'),
        (COMPLETED, 'Complete'),
        (SHARE, 'Share')
    ]
    action = models.CharField(max_length=2, choices=ACTIONS)

    @staticmethod
    def save_log(action, user, item):
        user_item_log = UserItemActionLog()
        user_item_log.action = action
        user_item_log.user = user
        user_item_log.item = item
        user_item_log.save()

    class Meta:
        abstract = 'user_item_log'


class RatedItem(models.Model):
    rate = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        db_table = 'rated_item'


class SharedItem(UserItem):
    @staticmethod
    def shared_with(user):
        return [shared_item.item for shared_item in SharedItem.objects.filter(user=user)]

    class Meta:
        db_table = 'shared_item'


class Course(Item):
    instructor_set = models.ManyToManyField(Instructor, blank=True)
    resource_set = models.ManyToManyField(FileItem, blank=True)
    release_date = models.DateField(blank=True, null=True)

    class Meta:
        db_table = 'course'


class Sheet(Item):
    class Meta:
        db_table = 'sheet'


class NoteBook(Item):
    sheet_set = models.ManyToManyField(Sheet, blank=True)


class CourseElement(Sheet):
    sequence = models.IntegerField(blank=True, null=True)
    course_part = models.ForeignKey('CoursePart', on_delete=models.CASCADE)

    class Meta:
        db_table = 'course_element'
        ordering = ['sequence', ]


class School(Instructor):
    colloquial_name = models.CharField(max_length=8, blank=True, null=True)

    class Meta:
        db_table = 'school'


class CoursePart(models.Model):
    label = models.CharField(max_length=32, default='Week')
    title = models.CharField(max_length=64, blank=True, null=True)
    course = models.ForeignKey(Course, models.CASCADE)
    level = models.SmallIntegerField(default=1)
    sequence = models.SmallIntegerField(default=1)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'course_part'
        ordering = ['id', ]


class Cell(PolymorphicModel):
    sequence = models.IntegerField(blank=False, null=False)
    sheet = models.ForeignKey(Sheet, models.CASCADE)

    def type(self):
        return self.__class__.__name__[:-4]

    class Meta:
        db_table = 'cell'
        ordering = ['sequence', ]


class MediaCell(Cell):
    title = models.CharField(max_length=64, blank=True, null=True)
    url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True


class GraphicMediaCell(MediaCell):
    scale = models.FloatField(default=1)

    class Meta:
        abstract = True


class MarkdownCell(Cell):
    text = models.TextField(blank=True, null=True)

    def __str__(self):
        return (self.text[:75] + '...') if len(self.text) > 75 else self.text

    class Meta:
        db_table = 'markdown_cell'


class VideoCell(GraphicMediaCell):
    class Meta:
        db_table = 'video_cell'


class YoutubeCell(GraphicMediaCell):
    class Meta:
        db_table = 'youtube_cell'


class AudioCell(MediaCell):
    class Meta:
        db_table = 'audio_cell'


class FileCell(MediaCell):
    class Meta:
        db_table = 'file_cell'


class ImageCell(GraphicMediaCell):
    class Meta:
        db_table = 'image_cell'


class Folder(Content):
    name = models.CharField(max_length=128, blank=True, null=True)
    parent = models.ForeignKey('Folder', models.CASCADE, null=True)

    def __str__(self):
        return self.name

    def siblings(self):
        result = []
        if self.parent:
            result = [folder for folder in self.parent.folder_set.filter(owner=self.owner) if folder.id != self.id and folder.id != 1]
        return result

    def ascendants(self):
        result = []
        folder = self
        while folder.id != 1:
            result.append(folder.parent)
            folder = folder.parent

        result.reverse()
        print(result)
        return result

    class Meta:
        db_table = 'folder'
        ordering = ['id', ]


class MultipleChoiceInputCell(Cell):
    class Meta:
        db_table = 'multiple_choice_input_cell'


class NumericalInputCell(Cell):
    answer = models.FloatField(blank=True, null=True)

    class Meta:
        db_table = 'numerical_input_cell'


class OpenEndedInputCell(Cell):
    answer = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'open_ended_input_cell'


class Proposition(models.Model):
    input_cell = models.ForeignKey(MultipleChoiceInputCell, on_delete=models.CASCADE)
    statement = models.TextField(blank=True, null=True)
    is_true = models.BooleanField(default=False)

    class Meta:
        db_table = 'proposition'

libr/models.py
from django.db import models
from klazor.models import FileItem
# Create your models here.


class Publisher(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'publisher'


class Author(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'author'


class Narrator(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'narrator'


class Document(FileItem):
    description = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'document'


class Book(Document):
    release_date = models.DateField(blank=True, null=True)
    isbn = models.CharField(max_length=13, blank=True, null=True, unique=True)
    publisher = models.ForeignKey(Publisher, models.CASCADE)
    author_set = models.ManyToManyField(Author)
    lang_alpha2 = models.CharField(max_length=2, blank=True, null=True)

    class Meta:
        db_table = 'book'


class TextBook(Book):
    nb_pages = models.PositiveSmallIntegerField(blank=True, null=True)

    class Meta:
        db_table = 'paper_book'


class AudioBook(Book):
    narrator_set = models.ManyToManyField(Author, blank=True)

    class Meta:
        db_table = 'audio_book'


class DocumentFile(Document):
    nb_pages = models.PositiveSmallIntegerField(blank=True, null=True)

    class Meta:
        db_table = 'document_file'

libr/views.py
from django.shortcuts import render
from libr.models import Book
from klazor.models import Tag
# Create your views here.


def index(request):
    books = Book.objects.all()
    tags = Tag.objects.all()
    return render(request, 'pages/index_libr.html', {'books': books, 'tags': tags})

templates/pages/course.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} {{ course.title }} {% endblock %}
{% block style %} <link rel="stylesheet" href="{% static 'css/course.css' %}"> {% endblock %}
{% block content %}
    {% include 'includes/components/modals/add_course_part.html' %}
    {% include 'includes/components/modals/add_course_element.html' %}
    <div class="base-container">
    <div class="row">
        <div class="col-md-3">
        {% include 'includes/components/navs/course_nav.html' with course=course %}
        </div>
        <div class="col-md-9">
            <h1 class="text-center">{{ course.title}}</h1>
            <hr>
            <div class="container">
                <section>
                    <h2 class="text-muted">Contenu du cours <button class="float-right btn p-0" data-toggle="modal" data-target="#addCoursePartModal"><i class="text-secondary fa fa-plus"></i> Partie</button></h2><br>
                    {% for coursepart in course.coursepart_set.all  %}
                        <div class="row">
                            <h3 class="col-md-2">{{ coursepart.label }} {{ coursepart.sequence }} :</h3>
                            <h3 class="col-md-10">{{ coursepart.title }} <button class="float-right btn p-0" data-toggle="modal" data-target="#addCourseElementModal" onmouseover="changeAddCourseElementModal({{ coursepart.id }})"><i class="text-primary fa fa-plus"></i> Elément</button> </h3>
                        </div>
                        <ul class="row">
                            {% for courseelement in coursepart.courseelement_set.all %}
                                <li class="col-md-9 offset-3"><a href="{% url 'course-element' course.id coursepart.sequence courseelement.sequence %}">{{ courseelement.title }} {% if courseelement.completed %} <i class="fa fa-check-circle text-success"></i> {% endif %}</a></li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                </section>
                <hr>
                {% include 'includes/components/course_resources.html' with resources=course.resource_set.all %}
                <hr>
                {% include 'includes/components/course_instructors.html' with instructors=course.instructor_set.all %}
            </div>
        </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        function changeAddCourseElementModal(id){
            document.querySelector('#addCourseElementForm').action = '/course-part/' + id + '/add-element/'
        }
    </script>
{% endblock %}

templates/pages/course_element.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block style %}
    {% include 'includes/styles/highlightjs_style.html' %}
    {% include 'includes/styles/codemirror_style.html' %}
    <link rel="stylesheet" href="{% static 'css/course.css' %}">
    <link rel="stylesheet" href="{% static 'css/sheet.css' %}">
    <link rel="stylesheet" href="{% static 'css/course_element.css' %}">
{% endblock %}
{% block title %} {{ course_element.title }} {% endblock %}
{% block content %}
    <div class="base-container">
        <div class="row">
            <div class="col-md-3">
                {% include 'includes/components/navs/course_nav.html' with course=course_element.course_part.course course_element=course_element %}
            </div>
            <div class="col-md-9">
                {% include 'includes/components/sheet.html' with sheet=course_element %}
               {% comment %} <form action="{% url 'check-course-element' course_element.id %}" method="post">
               TODO : Figure out how to deal with the check course element: mark as completed
                    {% csrf_token %}
                    <button class="float-right my-3 btn {% if course_element.completed %} {{ ' btn-secondary ' }} {% else %} {{ ' btn-info ' }}{% endif %}">
                        {% if not course_element.completed %} <i class="fa fa-check"></i>
                            {{ 'Mark as completed' }} {% else %} <i class="fa fa-undo"></i>
                            {{ ' Unmark as completed ' }}{% endif %}
                    </button>
                </form>{% endcomment %}
                <nav class="my-3">
                    <ul class="pagination">
                        <li class="page-item">
                            <a class="page-link {% if course_element.sequence == 1 %} {{ 'btn disabled text-secondary' }} {% endif %}"
                               href="{% url 'course-element' course_element.course_part.course.id course_element.course_part.sequence course_element.sequence|add:-1 %}"
                               aria-label="Previous">
                                <span aria-hidden="true">&laquo; Previous</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link"
                               href="{% url 'course-element' course_element.course_part.course.id course_element.course_part.sequence course_element.sequence|add:1 %}"
                               aria-label="Next">
                                <span aria-hidden="true">Next &raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <hr>
                {% include 'includes/components/course_resources.html' with resources=course_element.course_part.course.resource_set.all %}
                <hr>
                {% include 'includes/components/course_instructors.html' with instructors=course_element.course_part.course.instructor_set.all %}
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    {% include 'includes/scripts/sheet_script.html' with sheet=course_element %}
{% endblock %}

templates/pages/edit_course.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <h1> Edit Course </h1>
        {% include 'includes/components/modals/add_tag.html' %}
        {% include 'includes/components/modals/add_instructor.html' %}
        <form action="{% url 'save-course' course.id %}" method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-success float-right" type="submit">Save and Continue <i
                    class="fa fa-arrow-right"></i></button>
        </form>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'axios/dist/axios.min.js' %}"></script>
    <script src="{% static 'js-cookie/src/js.cookie.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    <script>
        // Add addTagBtn
        addTagBtnString = `<a href="#addTagModal" class="btn p-0" data-toggle="modal" data-target="#addTagModal"> <i class="fa fa-plus text-success"></i> </a>`
        addTagBtn = htmlToElement(addTagBtnString)
        document.querySelector('#div_id_tag_set').firstElementChild.append(addTagBtn)

        // Add addInstructorBtn
        addInstructorBtnString = `    <a href="#addInstructorModal" class="btn p-0" data-toggle="modal" data-target="#addInstructorModal"> <i class="fa fa-plus text-success"></i> </a>`
        addInstructorBtn = htmlToElement(addInstructorBtnString)
        document.querySelector('#div_id_instructor_set').firstElementChild.append(addInstructorBtn)

        function saveTag() {
            let csrftoken = Cookies.get('csrftoken')
            let tagFormData = new FormData()
            let tagName = document.querySelector('#tag-name').value
            tagFormData.set('tag-name', tagName)
            axios({
                method: 'post',
                url: '/tag/add/',
                data: tagFormData,
                headers: {
                    "X-CSRFToken": csrftoken,
                    "Content-Type": "multipart/form-data"
                }
            }).then((response) => {

                {#document.querySelector('#id_tag_set').firstElementChild.append(addTagBtn)#}
                console.log(response)
                let savedTagId = response.data['id']
                let savedTagName = response.data['name']
                let tagOptionString = `<option value="${savedTagId}" selected> ${savedTagName}</option>`
                let tagOption = htmlToElement(tagOptionString)
                document.querySelector('#id_tag_set').append(tagOption)
                $('#addTagModal').modal('hide')
            }).catch((error) => {
                console.log(error)
            })
        }

        function saveInstructor() {
            let csrftoken = Cookies.get('csrftoken')
            let instructorFormData = new FormData()
            let instructorName = document.querySelector('#instructor-name').value
            let instructorLink = document.querySelector('#instructor-link').value
            instructorFormData.set('instructor-name', instructorName)
            instructorFormData.set('instructor-link', instructorLink)
            axios({
                method: 'post',
                url: '/instructor/add/',
                data: instructorFormData,
                headers: {
                    "X-CSRFToken": csrftoken,
                    "Content-Type": "multipart/form-data"
                }
            }).then((response) => {

                {#document.querySelector('#id_instructor_set').firstElementChild.append(addInstructorBtn)#}
                console.log(response)
                let savedInstructorId = response.data['id']
                let savedInstructorName = response.data['name']
                let instructorOptionString = `<option value="${savedInstructorId}" selected> ${savedInstructorName}</option>`
                let instructorOption = htmlToElement(instructorOptionString)
                document.querySelector('#id_instructor_set').append(instructorOption)
                $('#addInstructorModal').modal('hide')
            }).catch((error) => {
                console.log(error)
            })
        }

    </script>
{% endblock %}

templates/pages/folder.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} {{ folder.name }} {% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/tiny.css' %}">
    <link rel="stylesheet" href="{% static 'css/folder.css' %}">
{% endblock %}

{% block content %}
    {% include 'includes/components/modals/add_folder.html' with parent_id=folder.id %}
    {% include 'includes/components/modals/add_folder_files.html' with folder_id=folder.id %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                {% include 'includes/folder_breadcrumb.html' with folder=folder %}
            </div>
        </div>
        {% block quick_access %} {% endblock %}
        {% include 'includes/folder_content.html' with folder=folder %}
    </div>
{% endblock %}F
{% block script %}
    <script src="{% static 'js-cookie/src/js.cookie.js' %}"></script>
    <script src="{% static 'axios/dist/axios.min.js' %}"></script>
    <script src="{% static 'js/tiny.js' %}"></script>
    <script src="{% static 'js/folder.js' %}"></script>
    <script>
       window.oncontextmenu = (event) => openFolderContextMenu(event, {{ folder.id }})
    </script>
{% endblock %}

templates/pages/folder_editor.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block style %}
    {% include 'includes/styles/highlightjs_style.html' %}
    {% include 'includes/styles/codemirror_style.html' %}
    <link rel="stylesheet" href="{% static 'css/sheet.css' %}">
    <link rel="stylesheet" href="{% static 'css/folder_editor.css' %}">
{% endblock %}
{% block title %} {{ folder.name }} {% endblock %}
{% block content %}
    <div class="base-container">
        <div class="row">
            <div class="col-md-3">
                {% include 'includes/components/navs/folder_editor_nav.html' with folder=folder courses=courses sheets=sheets file_items=file_items sheet_id=active_sheet.id %}
            </div>
            <div class="col-md-9">
                {% include 'includes/components/sheet.html' with sheet=active_sheet %}
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    {% include 'includes/scripts/sheet_script.html' with sheet=active_sheet %}
{% endblock %}

templates/pages/libr.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/welcome.css' %}">
    <link rel="stylesheet" href="{% static 'css/tiny.css' %}">
{% endblock %}
{% block title %} Libr {% endblock %}
{% block content %}
    <div class="px-5">
    <div class="row">

    </div>
    <div class="row">
        <div class="col-2">
            <h1>Filtres</h1>
            <ul class="list-group" style="height:95vh; overflow-y: scroll">
                {% for tag in tags.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ tag.name }}
                    <input type="checkbox">
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-7"></div>
        <div class="col-3"></div>
    </div>
    </div>
    {% comment %}<div class="container">
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">ISBN</th>
                <th scope="col">Author(s)</th>
                <th scope="col">Title</th>
                <th scope="col">Publisher</th>
                <th scope="col">Year</th>
                <th scope="col">Pages</th>
                <th scope="col">Language</th>
                <th scope="col">Size</th>
                <th scope="col">Extension</th>
            </tr>
            </thead>
            <tbody>
            {% for book in books %}
                <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ book.isbn }}</td>
                <td>{{ book.author_set.all.first.name }}</td>
                <td><a href="{{ book.file.url }}">{{ book.title }}</a></td>
                <td>{{ book.publisher.name }}</td>
                <td>{{ book.year }}</td>
                <td>{{ book.nb_pages }}</td>
                <td>{{ book.lang_alpha2}}</td>
                <td>{{ book.file.file|filesizeformat }}</td>
                <td> pdf </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>{% endcomment %}
{% endblock %}

templates/pages/school_course.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} {{ school_course.title }} {% endblock %}
{% block style %} <link rel="stylesheet" href="{% static 'css/course.css' %}"> {% endblock %}
{% block content %}
    <div class="base-container">
    <div class="row">
        <div class="col-md-3">
        {% include 'includes/components/navs/school_course_nav.html' with school_course=school_course%}
        </div>
        <div class="col-md-9">
            <h1 class="text-center">{{ school_course.title}}</h1>
            <hr>
            <div class="container">
                <section>
                    <h2 class="text-muted">Contenu du cours </h2><br>
                    {% for coursepart in school_course.coursepart_set.all  %}
                        <div class="row">
                            <h3 class="col-md-2">{{ coursepart.label }} {{ coursepart.sequence }} :</h3>
                            <h3 class="col-md-10">{{ coursepart.title }}</h3>
                        </div>
                        <ul class="row">
                            {% for courseelement in coursepart.courseelement_set.all %}
                                <li class="col-md-9 offset-3"><a href="{% url 'school-course-item' courseelement.id %}">{{ courseelement.title }} {% if courseelement.completed %} <i class="fa fa-check-circle text-success"></i> {% endif %}</a></li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                </section>
                <hr>
                {% include 'includes/components/course_resources.html' with resources=school_course.resource_set.all %}
                <hr>
                {% include 'includes/components/course_instructors.html' with instructors=school_course.instructor_set.all %}
            </div>
        </div>
        </div>
    </div>
{% endblock %}

templates/pages/sheet.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block style %}
    {% include 'includes/styles/highlightjs_style.html' %}
    {% include 'includes/styles/codemirror_style.html' %}
    <link rel="stylesheet" href="{% static 'css/course.css' %}">
    <link rel="stylesheet" href="{% static 'css/sheet.css' %}">
{% endblock %}
{% block title %} {{ sheet.title }}{% endblock %}
{% block content %}
    <div class="container">
        {% include 'includes/sheet_breadcrumb.html' with sheet=sheet %}
        {% include 'includes/components/sheet.html' with sheet=sheet %}
    </div>

{% endblock %}
{% block script %}
    {% include 'includes/scripts/sheet_script.html' %}
{% endblock %}

templates/pages/welcome.html
{% extends 'pages/folder.html' %}
{% block quick_access %}
    <hr>
    <div class="quick-access-container row">
            <div class="col-12">
                <h1> Accès rapide <small><i class="fa fa-bolt"></i></small>
                </h1>
            </div>
            {% for sheet in quick_access %}
                {% if sheet.folder %}
                    <div class="col-lg-2  col-md-3">
                        {% include 'includes/components/tiny/tiny_recent_sheet.html' with sheet=sheet %}
                    </div>
                {% else %}
                    <div class="col-lg-2  col-md-3">
                        {% include 'includes/components/tiny/tiny_recent_course_element.html' with course_element=sheet.courseelement %}
                    </div>
                {% endif %}

            {% endfor %}
        </div>
{% endblock %}